import LoginForm from "@/components/login-form";
import { Metadata } from "next";
import Link from "next/link";
import Logo from "@/components/logo";

export const metadata: Metadata = {
  title: `Login | ${process.env.NEXT_PUBLIC_APP_NAME || "My Uninotes"}`,
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="h-full relative flex-col items-center justify-center md:grid lg:max-w-none lg:grid-cols-2 lg:px-0">
      <div className="relative hidden h-full flex-col bg-white text-black border-4 border-black p-10 lg:flex">
        <div className="absolute inset-0 bg-secondary" />
        <div className="relative z-20 flex items-center text-xl font-extrabold uppercase tracking-wide border-b-4 border-black pb-4">
          <Logo withText />
        </div>
        <div className="relative z-20 mt-auto">
          <div className="text-2xl font-black mt-10 bg-black text-white p-3 inline-block border-2 border-black">
            Condividi il sapere, supera gli esami. Insieme.
          </div>
          <div className="mt-4 text-base font-medium bg-white text-black border-2 border-black p-4 max-w-md">
            My Uninotes è la piattaforma gratuita ed open-source per studenti
            universitari: carica, cerca e scarica appunti senza distrazioni.
            Tutto quello che ti serve, in un solo posto.
          </div>
        </div>
      </div>
      <div className="p-8">
        <div className="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
          <div className="flex flex-col space-y-2 text-center">
            <h1 className="text-3xl font-bold tracking-tight">
              Accedi a My Uninotes
            </h1>
            <p className="text-sm text-muted-foreground">
              Inserisci le tue credenziali per accedere al tuo account
            </p>
          </div>
          <LoginForm />
          <p className="px-6 text-center text-sm text-muted-foreground">
            <Link
              href="/register"
              className="underline underline-offset-4 hover:text-primary"
            >
              Non hai un account? Registrati
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
