name: Pull Request Target Branch Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-target-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR targets 'staging' branch
        if: github.event.pull_request.base.ref != 'staging'
        run: |
          echo "Error: Pull requests must target the 'staging' branch."
          exit 1
